name: CountOnMeServer

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: countonme-server
  ECS_SERVICE: CountOnMe-Server-service-2y7187a8
  ECS_CLUSTER: CountOnMe
  ECS_TASK_DEFINITION: ./aws/taskDefinition.json
  CONTAINER_NAME: docker

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 
      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          repository: misterkillerman/CountOnMeServer
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t 730335643718.dkr.ecr.ap-southeast-1.amazonaws.com/countonme-server --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        
    - name: Update ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: CountOnMe-Server
        service: CountOnMe-Server-service-2y7187a8
        cluster: CountOnMe
        wait-for-service-stability: true
        force-new-deployment: true
