name: CountOnMeServer

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECS_CLUSTER: CountOnMe
  ECR_REGISTRY_URL: 730335643718.dkr.ecr.ap-southeast-1.amazonaws.com

  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.AWS_EC2_HOST }}
  USER: ${{ secrets.AWS_EC2_USER }}
  
  ECR_TRANSACTIONS_REPOSITORY: count-on-me/transactions
  ECS_TRANSACTIONS_TASK_DEFINITION: TransactionService/aws/taskDefinition.json
  TRANSACTIONS_CONTAINER_NAME: CountOnMe-Server-Transactions
  ECR_USERS_REPOSITORY: count-on-me/users
  ECS_USERS_TASK_DEFINITION: UserService/aws/taskDefinition.json
  USERS_CONTAINER_NAME: CountOnMe-Server-Users

jobs:
  build-transactions:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      image_tag: ${{ steps.build-image.outputs.image_tag }}

    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 
  
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build -f ./TransactionService/Dockerfile --platform linux/amd64,linux/arm64 -t $ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG --push .
        echo "image=$ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG"
        echo "image=$ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT


  deploy-transactions-to-ecr:
    runs-on: ubuntu-latest
    needs: build-transactions
    steps:    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TRANSACTIONS_TASK_DEFINITION }}
        container-name: ${{ env.TRANSACTIONS_CONTAINER_NAME }}
        image: ${{ needs.build-transactions.outputs.image }}

  deploy-transactions-to-ec2:
    runs-on: ubuntu-latest
    needs: deploy-transactions-to-ecr
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_NAME: transactions
        run: |
          echo "${{ env.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ env.USER }}@${{ env.HOST }} <<EOF
            sudo service docker start
            sudo aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

            echo "$ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG"

            docker stop $DOCKER_NAME || true
            docker image prune -f
            docker rmi -f $(docker images | grep $DOCKER_NAME) || true
            docker rm $DOCKER_NAME || true

            docker pull $ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG

            docker run -d --name $DOCKER_NAME -p 8080:8080 $ECR_REGISTRY_URL/$ECR_TRANSACTIONS_REPOSITORY:$IMAGE_TAG
          EOF

  build-users:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 
  
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build -f ./UserService/Dockerfile --platform linux/amd64,linux/arm64 -t $ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG --push .
        echo "image=$ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG"
        echo "image=$ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  
  deploy-users-to-ecr:
    runs-on: ubuntu-latest
    needs: build-users
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_USERS_TASK_DEFINITION }}
        container-name: ${{ env.USERS_CONTAINER_NAME }}
        image: ${{ needs.build-users.outputs.image }}

  deploy-users-to-ec2:
    runs-on: ubuntu-latest
    needs: deploy-users-to-ecr
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_NAME: users
        run: |
          echo "${{ env.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ env.USER }}@${{ env.HOST }} <<EOF
            sudo service docker start

            sudo aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

            echo "$ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG"
            
            docker stop $DOCKER_NAME || true
            docker image prune -f
            docker rmi -f $(docker images | grep $DOCKER_NAME) || true
            docker rm $DOCKER_NAME || true

            docker pull $ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG
            
            docker run -d --name $DOCKER_NAME -p 8081:8081 $ECR_REGISTRY_URL/$ECR_USERS_REPOSITORY:$IMAGE_TAG
          EOF
